controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_user_mi_coleccion:
    path: "/api/miColeccion"
    controller: 'App\Controller\UserController::miColeccion'
    methods: ["GET"]
